### ISSUE TITLE
Skaffold.yml and relevant k8s helm chart files need updating

### ISSUE THREAD

**Issue by btassone** [YaleSpinup/api-tmpl#13]
* https://github.com/YaleSpinup/api-tmpl/blob/e876330d7df35637d40deeb9201b56a1e78b1046/skaffold.yaml.tmpl#L1 - Requires an update to skaffold/v2beta28
* https://github.com/YaleSpinup/api-tmpl/blob/e876330d7df35637d40deeb9201b56a1e78b1046/skaffold.yaml.tmpl#L28C9-L28C9 - Should be removed in favor of below
  ```
        setValues:
          probePath: '/v1/{{ .AppName }}/ping'
          ingress.rules[0].paths[0]: '/v1/{{ .AppName }}'
  ```
* https://github.com/YaleSpinup/api-tmpl/blob/master/k8s/values.yaml.tmpl - Can be removed
* https://github.com/YaleSpinup/api-tmpl/blob/e876330d7df35637d40deeb9201b56a1e78b1046/k8s/api/templates/ingress.yaml#L5 - needs to be updated to apiVersion: networking.k8s.io/v1
* https://github.com/YaleSpinup/api-tmpl/blob/e876330d7df35637d40deeb9201b56a1e78b1046/k8s/api/templates/ingress.yaml#L34 - needs to be updated to support networking.k8s.io/v1
  ```
            - path: {{ . }}
              pathType: Prefix
              backend:
                service:
                  name: {{ $fullName }}
                  port:
                    number: {{ $svcPort }}
  ```
